name: Deploy to Azure App Service using ARM template

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Copy ARM template and parameter file to GitHub workspace
        run: |
          cp "C:\Users\samarth_birajdar\echo_bot\deploymentTemplates\template-with-new-rg.json" deploymentTemplates/
          cp "C:\Users\samarth_birajdar\echo_bot\deploymentTemplates\parameters-template-with-new-rg.json" deploymentTemplates/

      - name: Deploy ARM template
        run: az deployment group create --resource-group EchoBot --template-file deploymentTemplates/template-with-new-rg.json --parameters @deploymentTemplates/parameters-template-with-new-rg.json

      - name: Deploy to Azure App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'AppEchBotTest'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_ycHYG4tb79fe2a9fggCniTFyudFKkYH0RwfidKTqYsnrxkAimqsvuk63lYfh }}
